spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: com.example.study.model
  mapperLocations: classpath:mapper/*.xml

jwt:
  tokenHeader: Authorization
  secret: 12345678901234567890123456789012
  expiration: 604800 # 7天
  tokenHead: 'Bearer '

security:
  ignored: # 路径白名单
    urls:
      - /login
      - /register

logging:
  level:
    com.example.study.mapper: debug
    com.example.study.controller: debug